services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend1:
    image: aalsaa/presta-banco-backend:lastest
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    expose:
      - "8090"

  backend2:
    image: aalsaa/presta-banco-backend:lastest
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    expose:
      - "8090"

  backend3:
    image: aalsaa/presta-banco-backend:lastest
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    expose:
      - "8090"

  frontend1:
    image: aalsaa/presta-banco-frontend:lastest
    networks:
      - app-network

  frontend2:
    image: aalsaa/presta-banco-frontend:lastest
    networks:
      - app-network
  
  frontend3:
    image: aalsaa/presta-banco-frontend:lastest
    networks:
      - app-network
  
  nginx-backend:
    image: nginx:latest
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    ports:
      - "8090:8090" 
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - app-network

  nginx-frontend:
    image: nginx:latest
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
